---
name: Build and Push React Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: lesson-087
      PROJECT_ID: devopsbyexample-325402
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t nao-app:latest .

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v major

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-west2-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag nao-app:latest gcr.io/6b58f6201069/nao-app:latest
        docker tag nao-app:latest gcr.io/6b58f6201069/nao-app:$GIT_TAG
        docker push gcr.io/6b58f6201069/nao-app:latest
        docker push gcr.io/6b58f6201069/nao-app:$GIT_TAG

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag nao-app:latest us-west2-docker.pkg.dev/6b58f6201069/images/$IMAGE_NAME:latest
        docker tag nao-app:latest us-west2-docker.pkg.dev/6b58f6201069/images/$IMAGE_NAME:$GIT_TAG
        docker push us-west2-docker.pkg.dev/6b58f6201069/images/nao-app:latest
        docker push us-west2-docker.pkg.dev/6b58f6201069/images/nao-app:$GIT_TAG